Setup/InstallData.php

Fix error during installation

---

Helper/Api.php

fix api validation and config retrieval for Magento instance with several websites

---

Mail/Transport.php
Plugin/SubscribeIntercept.php

This fixes newsletter subscription for non-customers.

Fix Newsletter Subscribe

---

Helper/Api.php
etc/adminhtml/system.xml

This should address proper scope configuration retrieval. 
Also fixes view of API Credential Validation in Store view of system configuration.

Improving Scope Config Retrieval

---

Helper/Settings.php
etc/template_config.xml

Adds configuration options for guest order confirmation

Fixing support for guest order template

---

Helper/Settings.php
etc/template_config.xml

This fixes the guest shipment issue for isGuest

Fixes #IN-900 to enable shipment emails for guest and logged in users

---

Block/Frontend/Js.php
Helper/ClientManager.php
etc/adminhtml/system.xml
view/frontend/layout/default.xml
view/frontend/templates/js.phtml
view/frontend/web/spm.js

* Improves ease of implementation of Sailthru Javascript with new Store Config setting group
* Updates descriptions around API and Javascript setup.

IN-1006 Easy JS Setup

---

Mail/Transport.php
etc/di.xml

Implemented a fix that would restore email sending functionality and that would work both for Magento v2.1.x and Magento v2.2.x

Update extension to support Magento v2.2.x

---

Plugin/ProductIntercept.php

Sailthru API doesn't accept negative inventory.

Collapse negative inventory to 0 inventory.

---

Helper/Customer.php
Helper/Settings.php
Helper/VarHelper.php
Model/Config/Source/ValidatedSnakeOrCamel.php
Observer/Frontend/CustomerAccountEdit.php
Observer/Frontend/CustomerRegistered.php
Plugin/SubscribeIntercept.php
etc/adminhtml/system.xml
etc/config.xml

https://sailthru.atlassian.net/browse/IN-1123
Added functionality to the SailMage plugin to switch between camelCase and snake_case for vars. This reflects on creating a user and changing the user's information.

In 1123/switch between camel snake case

---

Mail/Transport.php
Model/Config/Source/SailthruTemplates.php
etc/template_config.xml

Overriding Sailthru send when transactionals are enabled for any template.

In 1125/override sailthru send

---

Observer/Frontend/CustomerLoggedIn.php

On login, the app was looking for SID but didn't have a fallback ID to use with the Sailthru API and was causing backend errors (invisible to customers). This makes sure there's an email fallback, adds a typehint for the customer object, and constraints the scope of the Sailthru API call.

Patch for users logging in who don't have Sailthru ID saved yet.

---

Helper/Api.php
Helper/ProductData.php
Mail/BackendTemplate.php
Mail/Template.php
Mail/Transport.php
Model/Config/Source/TaggableAttributes.php
Model/Cron.php
Plugin/ProductIntercept.php
README.md
etc/adminhtml/system.xml
etc/di.xml

- Send Magento 2 Admin Emails
- Sync Product Data Nightly to Sailthru
- Configurable Product Attributes for Product Sync

Sailthru M2 SOW 4 Change request

---

Mail/Template.php

Fix account email address update crush on sailthru

Fix issue 56 - account email address update

---

Mail/Template.php
composer.json
etc/module.xml

Fixes https://github.com/sailthru/sailthru-magento2-extension/issues/56

Fix for broken update customer email and version update.

---

Helper/Settings.php
Helper/Templates.php
Mail/Template.php
Model/Cron.php
Model/SailthruTemplates.php
etc/adminhtml/system.xml
etc/config.xml
etc/crontab.xml
etc/template_config.xml

- Addressed SAIL-19 Fix parse directive values
- Addressed SAIL-18 Fix getting Sailthru templates and register RMA templates
- Addressed SAIL-21 Implemention cache of Sailthru templates and cron

SAIL-18, SAIL-19, SAIL-21

---

Helper/Shipment.php
Observer/OrderSave.php

- IN-1307 Magento: Investigate Client Shipping Issue #65
- IN-1306 Magento: Add Store ID as item-level var in purchases

[IN-1306] [IN-1307] Add Store ID as item-level var in purchases + Fix empty item

---

Model/SailthruTemplates.php
composer.json
etc/module.xml

- logging message change from Frendino
- minor version bump to 2.0.4

Frendino sail 29 prod changes

---

Plugin/ProductIntercept.php
composer.json

- Added PHP 7.4 support
- Fixed get stock qty when importing sailthru products via CLI

Addressed SAIL-30: Upgrade extension to support M2 v2.4.2 and PHP 7.4

---

Logger.php
Mail/Filter.php
composer.json
etc/module.xml

- Fixed Warning: var_export does not handle circular references in ./vendor/sailthru/sailthru-magento2-extension/Logger.php on line 20 in /var/www/html/vendor/magento/framework/App/ErrorHandler.php:61

QA Changes: CHA-843 502 error when invalid email provided during customer registration

---

composer.json
etc/adminhtml/system.xml
etc/module.xml

- Updated verbiage for the new settings

QA Change: SAIL-35 Remove the data from Sailthru when it's been deleted in Magento

---

Helper/Api.php
Helper/Product/PostContent.php
Helper/ProductData.php
Helper/ScopeResolver.php
Helper/Templates.php
Logger.php
MageClient.php
Mail/Queue/EmailSendProcessor.php
Model/Cron.php
Observer/OrderSave.php
README.md
composer.json
etc/adminhtml/system.xml
etc/module.xml

Versions we Support:
- 2.3.5+
- 2.4.0+

Upgrade extension to support M2 v2.4.5 and PHP 8.1

---

Observer/Frontend/CustomerRegistered.php
composer.json
etc/adminhtml/system.xml
etc/module.xml

https://sailthru.atlassian.net/browse/INT-856 
When the subscribe to newsletter option is unchecked, it will display the opt-out marketing functionality, which is implemented by passing an opt-out email flag.

[INT-856] opt-out-marketing-functionality-implemented

---

Observer/Frontend/CustomerRegistered.php
composer.json
etc/adminhtml/system.xml
etc/module.xml

Reverts sailthru/sailthru-magento2-extension#97

Revert "[INT-856] opt-out-marketing-functionality-implemented"

---

Observer/Frontend/CustomerRegistered.php
composer.json
etc/module.xml

INT-902
Added functionality to enable marketing opt-in and opt-out flags in the user API. Updated relevant endpoints and adjusted user data handling accordingly.

marketing opt-in/opt-out flag in user API

---

composer.json
etc/module.xml

Reverts sailthru/sailthru-magento2-extension#105

Revert "[INT-1024] Latest version release."

---

Plugin/CartIntercept.php

Reverts sailthru/sailthru-magento2-extension#104

Revert "[INT-1024] Added a fix to resolve Dayspring client's addtocart issue while sailthru_hid cookie set to do-not-track."

---

Observer/Frontend/CustomerRegistered.php
composer.json
etc/module.xml

Fix of Dayspring issues related with the Optout and Optin email flag for user account.

[INT-1076] Fix of Dayspring issues related with the Optout and Optin email flag for user account.
